server:
  port: 8888

management:
  security:
    enabled: false

spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/william-carvalho/config-repo.git
  rabbitmq:
    host: localhost
    port: 5672    
    
security:
  user:
    name: configUser
    password: configPassword
    role: SYSTEM
